@startuml YouTube_Activity_Diagram

start

:Открытие YouTube;

if (Пользователь авторизован?) then (да)
  :Загрузка персонального профиля;
  :Получение истории просмотров;
else (нет)
  :Гостевой режим;
endif

:Показ главной страницы;

:Выбор видео (поиск / рекомендации / тренды);

:Запрос видео метаданных;
:Запрос рекомендованных видео;

fork
  :Загрузка видеопотока через CDN;
fork again
  :Загрузка комментариев;
fork again
  :Загрузка рекомендаций;
fork again
  :Проверка рекламы;
end fork

:Начало воспроизведения видео;

while (Видео смотрится?) is (да)
  :Отправка watch progress;
  :Сбор телеметрии (watch time);
endwhile (нет)

if (Поставил лайк/дизлайк?) then (да)
  :Отправка реакции;
endif

if (Оставил комментарий?) then (да)
  :Сохранение комментария;
endif

:Обновление рекомендаций;

if (Видео досмотрено?) then (да)
  :Увеличение рейтинга видео;
  :Обновление ML модели рекомендаций;
endif

stop

@enduml